# Ansible inventory created from ['/home/zulu/Documents/network-automation-script/netlab/topology.yml', 'package:topology-defaults.yml']
#

%YAML 1.1
---
interfaces:
- ipv4: 10.1.0.2/30
  linkindex: 1
  type: p2p
  name: S1 -> R1
  ifindex: 1
  ifname: Ethernet0/1
  clab:
    name: Ethernet0/1
  mtu: 1500
  neighbors:
  - ipv4: 10.1.0.1/30
    ifname: Ethernet0/1
    node: R1
  _use_ip_mtu: true
clab:
  kind: cisco_iol
  type: l2
box: asifsyd/cisco_iol:l2-17.12.01
role: router
mtu: 1500
af:
  ipv4: true
mgmt:
  ifname: Ethernet0/0
  mac: 08:4f:a9:02:00:00
  ipv4: 192.168.121.102
hostname: clab-lab-S1
loopback:
  type: loopback
  neighbors: []
  virtual_interface: true
  ifindex: 0
  ifname: Loopback0
  ipv4: 10.0.0.2/32
