# Ansible inventory created from ['/home/zulu/Documents/network-automation-script/netlab/topology.yml', 'package:topology-defaults.yml']
#

%YAML 1.1
---
ansible_become_method: enable
ansible_network_os: ios
ansible_connection: network_cli
netlab_initial: always
netlab_ssh_args: -o KexAlgorithms=+diffie-hellman-group-exchange-sha1 -o 
  PubkeyAcceptedKeyTypes=ssh-rsa -o HostKeyAlgorithms=+ssh-rsa
ansible_user: admin
ansible_ssh_pass: admin
ansible_become_password: admin
netlab_device_type: iol
netlab_check_retries: 20
features:
  bfd: {}
  bgp:
    local_as: true
    vrf_local_as: true
    local_as_ibgp: true
    activate_af: true
    import:
    - ospf
    - isis
    - ripv2
    - connected
    - static
    - vrf
    community:
      standard:
      - standard
      extended:
      - extended
    confederation: true
  dhcp:
    client:
      ipv4: true
      ipv6: true
      routing: true
    relay: true
    vrf: true
    server: true
  eigrp: {}
  initial:
    ipv4:
      unnumbered: true
    ipv6:
      lla: true
      use_ra: true
    roles:
    - host
    - router
    - bridge
    mgmt_vrf: true
    min_mtu: 68
    min_phy_mtu: 1501
    max_mtu: 1500
  isis:
    import:
    - bgp
    - ospf
    - ripv2
    - connected
    - static
    unnumbered:
      ipv4: true
      ipv6: true
      network: true
  mpls:
    ldp: true
    bgp: true
    vpn: true
    6pe: true
  ospf:
    unnumbered: true
    import:
    - bgp
    - isis
    - ripv2
    - connected
    - static
    - vrf
    default:
      policy: true
    password: true
    priority: true
    timers: true
  ripv2:
    ipv4: true
    ipv6: true
    passive: true
    import:
    - bgp
    - isis
    - ospf
    - connected
    - static
    - vrf
  routing:
    policy:
      set:
        locpref: true
        med: true
        weight: true
        prepend: true
        community:
          standard: true
          append: true
          delete: clist
          delete_list: true
      match:
      - prefix
      - nexthop
      - aspath
      - community
    prefix: true
    aspath: true
    community:
      expanded: true
    static:
      vrf: true
      inter_vrf: true
      discard: true
  vlan:
    model: l3-switch
    svi_interface_name: BDI{vlan}
    subif_name: '{ifname}.{subif_index}'
    mixed_trunk: true
    native_routed: true
  vrf:
    ospfv2: true
    ospfv3: true
    bgp: true
    ripv2: true
    ripng: true
  gateway:
    protocol:
    - vrrp
  sr: {}
